In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R

tf_l2c_dummy = np.array(
    [
        [-0.3952076, -0.09230257, 0.91394271, 0.07686256],
        [-0.91807052, 0.00617267, -0.39636911, -0.15441064],
        [0.03094439, -0.9957119, -0.0871798, -0.1026438],
        [0.0, 0.0, 0.0, 1.0],
    ]
)

# Extract the 3x3 rotation matrix
rotation_matrix = tf_l2c_dummy[:3, :3]

# Convert to Rotation object
rotation = R.from_matrix(rotation_matrix)

# Extract Euler angles (e.g., XYZ order in radians)
euler_angles = rotation.as_euler(
    "xyz", degrees=True
)  # Change `degrees=True` for degrees

print("Euler Angles (XYZ order, in degrees):", euler_angles)

Euler Angles (XYZ order, in degrees): [ -95.0037841    -1.77326567 -113.29073048]


In [2]:
# Define Euler angles in degrees
euler_angles = np.array([-90, 0, -90])  # XYZ order in degrees

# Convert to rotation object
rotation = R.from_euler("xyz", euler_angles, degrees=True)

# Get quaternion
quat = rotation.as_quat()  # returns in xyzw order
print("Quaternion (xyzw):", quat)

# Get rotation matrix
rot_matrix = rotation.as_matrix()

# Create 4x4 transformation matrix (assuming translation is [0,0,0])
tf_matrix = np.eye(4)
tf_matrix[:3, :3] = rot_matrix

print("\n4x4 Transformation Matrix:")
print(tf_matrix)

# If you want to add a specific translation, you can do:
translation = np.array([0.07686256, -0.15441064, -0.1026438])
tf_matrix[:3, 3] = translation

print("\n4x4 Transformation Matrix with translation:")
print(tf_matrix)

Quaternion (xyzw): [-0.5  0.5 -0.5  0.5]

4x4 Transformation Matrix:
[[ 2.22044605e-16  2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

4x4 Transformation Matrix with translation:
[[ 2.22044605e-16  2.22044605e-16  1.00000000e+00  7.68625600e-02]
 [-1.00000000e+00  0.00000000e+00  2.22044605e-16 -1.54410640e-01]
 [ 0.00000000e+00 -1.00000000e+00  2.22044605e-16 -1.02643800e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
